name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        run: "deno lint"
      - name: Format check
        run: "deno fmt --check"
      - name: Test
        run: "deno run test-coverage"
